name: Followers hourly check

on:
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:

concurrency:
  group: followers-cron
  cancel-in-progress: true

permissions:
  contents: write

env:
  GH_USER: ${{ github.repository_owner }}
  CONFIG_PATH: .github/followers.json

jobs:
  check-followers:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: fetch followers via GitHub API
        id: fetch
        env:
          GH_TOKEN: ${{ github.token }}
          GH_USER: ${{ env.GH_USER }}
        run: |
          set -euo pipefail
          resp="$(curl -sS -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/users/${GH_USER}")"
          followers="$(printf '%s' "$resp" | jq -r '.followers')"
          if ! [[ "$followers" =~ ^[0-9]+$ ]]; then
            echo "failed to parse followers from API"; echo "$resp"; exit 1
          fi
          echo "followers=${followers}" >> "$GITHUB_OUTPUT"

      - name: prepare json
        id: prepare
        env:
          CONFIG_PATH: ${{ env.CONFIG_PATH }}
          GH_USER: ${{ env.GH_USER }}
          FOLLOWERS: ${{ steps.fetch.outputs.followers }}
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$CONFIG_PATH")"
          tmp="${CONFIG_PATH}.tmp"
          ts="$(date -u +%FT%TZ)"
          printf '{"type":"GitHub","login":"%s","followers":%s,"updatedAt":"%s"}\n' "$GH_USER" "$FOLLOWERS" "$ts" > "$tmp"

          if [ -f "$CONFIG_PATH" ]; then
            old="$(jq -r '.followers' "$CONFIG_PATH" || echo '')"
          else
            old=""
          fi
          echo "old=${old}" >> "$GITHUB_OUTPUT"

          if [ "$old" = "$FOLLOWERS" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            rm -f "$tmp"
          else
            mv "$tmp" "$CONFIG_PATH"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: commit and push if changed
        if: steps.prepare.outputs.changed == 'true'
        env:
          CONFIG_PATH: ${{ env.CONFIG_PATH }}
          FOLLOWERS: ${{ steps.fetch.outputs.followers }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$CONFIG_PATH"
          git commit -m "chore: update followers count to ${FOLLOWERS} [skip ci]"
          git push

      - name: extract project id from SA secret
        id: pid
        env:
          SA_JSON: ${{ secrets.GCP_SA_KEY }}
        run: |
          set -euo pipefail
          umask 177
          printf '%s' "${SA_JSON}" > sa.json
          pid="$(jq -r '.project_id' sa.json)"
          [ -n "$pid" ] && [ "$pid" != "null" ] || { echo "project_id not found in SA"; exit 1; }
          echo "project_id=$pid" >> "$GITHUB_OUTPUT"
          rm -f sa.json

      - name: auth to Google (FCM v1)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: send FCM push (every run)
        env:
          PROJECT_ID: ${{ steps.pid.outputs.project_id }}
          OWNER: ${{ env.GH_USER }}
          NEW: ${{ steps.fetch.outputs.followers }}
          OLD: ${{ steps.prepare.outputs.old }}
        run: |
          set -euo pipefail
          ACCESS_TOKEN="$(gcloud auth print-access-token)"
          old="${OLD:-0}"; new="${NEW:-0}"; delta=$(( new - old ))
          body="${OWNER}: ${old} → ${new} (Δ ${delta})"
          jq -n --arg body "$body" --arg delta "$delta" '{
            message:{
              topic:"followers_updates",
              android:{ notification:{ channel_id:"followers2" } },
              notification:{title:"GitHub followers", body:$body},
              data:{type:"followers", delta:$delta}
            }
          }' > body.json

          curl -sS -X POST \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            -H "Content-Type: application/json; charset=UTF-8" \
            -d @body.json \
            "https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send"